#
# Arm SCP/MCP Software
# Copyright (c) 2017-2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := stm32_clock
BS_LIB_SOURCES = mod_stm32_clock.c

include $(BS_DIR)/lib.mk
