#
# Arm SCP/MCP Software
# Copyright (c) 2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := SCMI Reset Protocol
BS_LIB_SOURCES := mod_scmi_reset.c

include $(BS_DIR)/lib.mk
